### ISSUE TITLE
Is Send implemented as a Promise?

### ISSUE THREAD

**Issue by ThorvaldAagaard** [cordova-sms/cordova-sms-plugin#163]
I am using the following code

```
    this.sms.send(this.phone, "Dear friend, please call me").then(() => {
      this.showMessage("Message Sent"));
    });
```

and the message is sent witout any problems, but the then() is never executed

I am using Ionic 

and the send method is declared as a Promise like this
```
    send(phoneNumber: string | string[], message: string, options?: SmsOptions): Promise<any>;
```

but could it be an error in the Ionic wrapper?

```
    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0 browser 5.0.1 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.3
    npm               : 5.5.1
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : D:\Documents\Android\Sdk

Misc:

    backend : pro
```

**Comment by dbaq** [comment]
hey @ThorvaldAagaard, 

You are correct, that probably comes from the wrapper (you should open an issue on their repo) since the SMS is sent and we don't use Promise here. 
Make sure you have the latest version of the wrapper and make sure you have the latest version of this plugin installed.

Cheers.

**Comment by skmasinda** [comment]
I read your message about the sms Cordova plug-in. It more likely is an
ionic problem and is suspect your '''this.showMessage''' function.

**Comment by ThorvaldAagaard** [comment]
That was also my first thought, but I tested it with just a console.log statement
```
    this.sms.send(this.phone, "Dear friend, please call me").then(() => {
      console.log("SMS Sent");
    });
```
hard to make any errors in that statement

But I was thinking about calling the function directly without using the Ionic wrapper

**Comment by skmasinda** [comment]
If you are trying to post a message saying "the sms was sent" try using the
toast controller. I think you are using ionic! That will help you better.
You may also try the alertcontroller too.

I am suggesting that because you can not run console.log() on your phone
and at the same time the browser can't run that Cordova plug-in. But if you
use those two controllers they will work on your device.

Let me know in case of a challenge

**Comment by ThorvaldAagaard** [comment]
Using ADB Plugin in chrome allows you to execute the app on a physical device, and still have all the logs going to the browsers javascript console, so I can see the promise is never resolved.

But anyway I have just dropped the idea of giving the user a confirmation message
