### ISSUE TITLE
Any insights on how to handle the new Google Play SMS restriction?

### ISSUE THREAD

**Issue by panchazo** [cordova-sms/cordova-sms-plugin#181]
"Google Play restricts the use of high risk or sensitive permissions, including the SMS or Call Log permission groups. "
...
Source: https://support.google.com/googleplay/android-developer/answer/9047303?hl=es

**Comment by alinebezzoco** [comment]
Hi @panchazo, 

I had to fill out the Google Play Permissions Declaration Form so that Google will open the permission for my application. I still have not gotten an answer from them so I'm waiting.

Link: https://docs.google.com/forms/d/e/1FAIpQLSfbmF-9G249UDLJZpEvJpjgwP8rjvvLyWyNYnFPrsqYjMNckg/viewform

**Comment by panchazo** [comment]
Thanks, I also submited that form for my app,  still didnt get any answer nor confirmation of the form submition...  we shall see what happens

**Comment by dbaq** [comment]
Yes it is all about the form. This plugin requires only the `SEND_SMS` permission.
