### ISSUE TITLE
SMS does not appear in messaging app

### ISSUE THREAD

**Issue by thkthkthk** [cordova-sms/cordova-sms-plugin#196]
Hi all,

We are using this plugin to populate sms content for customer to send. Recently some of our customers complain that the sms is not auto populate(just blank at the text field). Anyone have any idea on this ? Any help is much appreciated.

FYI, we already using the latest plugin. All the complains are from android phone only.

Regards,
HK

**Comment by askotx** [comment]
You are using an open source code for your customers for free -no cash- and for free -open, at least, you could try to solve making a pull request, no asking for solutions -again for free.

**Comment by dbaq** [comment]
hello @thkthkthk,

Like @askotx said correctly, this is an open source software. I don't have customers and I don't make any money from this code that I've been maintaining for a few years now.

Instead of opening a new issue, you should have replied to the existing one (#193) with more details like the android version(s), the phone version(s) and which SMS app is being used.

I am going to close and mark this one as a duplicate.
