### ISSUE TITLE
can't send multiparts message with intent = ''

### ISSUE THREAD

**Issue by dbaq** [cordova-sms/cordova-sms-plugin#7]
A pull request has been merge a few months ago https://github.com/aharris88/phonegap-sms-plugin/pull/40

it does not work if the intent value is empty.

**Comment by radiegtya** [comment]
Can You give the working code and add it to the documentation? And why should I use intent? I want direct send message :)

**Comment by dbaq** [comment]
If you want to send a message without opening the default intent, you have to set the intent value to empty (intent='').

So if you're sending multiparts message (more than 160 characters), we need to add the following permissions in the AndroidManifest.xml:
`<uses-permission android:name="android.permission.READ_PHONE_STATE" />`

I need to understand now why the callback method is called multiple times now (1 time per part of the message)

**Comment by dbaq** [comment]
hey @radiegtya, I pushed a fixed on a branch https://github.com/cordova-sms/cordova-sms-plugin/tree/wip_android_refactoring, it is fixing the issue with multiparts message in the default intent. And just one callback is fired when all the parts have been sent.

Since I refactored a big part of the android code, please test and let me know if it is working properly.

Install the new version by doing that:

```
cordova plugin rm org.apache.cordova.plugin.sms
cordova plugin add https://github.com/cordova-sms/cordova-sms-plugin.git#wip_android_refactoring
```

let me know. 

cheers

**Comment by dbaq** [comment]
@radiegtya, thanks for answering the following questions:
- how are you testing?
- which device?
- which android version?
- can you share your code?
- what is the error?
- how can I reproduce it?

**Comment by radiegtya** [comment]
Hi @dbaq, I'll answer Your questions:
- how are you testing?
  I am using meteor Js and cordova, so I just add the plugin and run it, when I am clicking sending button , it's not working
- which device?
  lg optimus l9
- which android version?
  honeycomb 3
- can you share your code?
  The code just exactly like what I was commented above
- what is the error?
  as I said, I can't see the error message, because I am directly install it on my phone rather using emulator. My Emulator cannot sending sms. lOl
- how can I reproduce it?
  Thats the part that I don't know. :D

**Comment by agarrharr** [comment]
Here's how you can get the javascript console when running Cordova on your device so that you can see the error: http://www.adamwadeharris.com/remote-debugging-in-phonegap-with-chrome-devtools/

**Comment by dbaq** [comment]
@radiegtya did you make it work?

**Comment by dbaq** [comment]
Closing this one. Feel free to reopen if the problem persists.
