### ISSUE TITLE
Open chooser instead of launching the default sms app

### ISSUE THREAD

**Issue by kukikiloke** [cordova-sms/cordova-sms-plugin#74]
Thanks for the good work, here's one suggestion/request from me though.

Perhaps we can open the chooser to display a list of sms apps on Android instead of launching the default sms app? as this might be more Android way of event handling?

Edit: The app will not show the list of messaging apps if no phone number is provided.

**Comment by agarrharr** [comment]
I believe that this is what the intent option is for:

```
android: {
    intent: 'INTENT'  // send SMS with the native android SMS messaging
    //intent: '' // send SMS without open any other app
}
```

**Comment by kukikiloke** [comment]
`intent: 'INTENT'`
If phone number(s) is/are provided, the plugin will display a list of messaging apps to handle the event
but if **phone number is not provided**, the plugin will open the default messaging app

That's what I observed on my Samsung S3 (5.1.1)

**Comment by dbaq** [comment]
Hello @kukikiloke,

You are right, the behavior is different. It is due to this condition https://github.com/cordova-sms/cordova-sms-plugin/blob/master/src/android/Sms.java#L79-L89

This code has been introduced almost 2 years ago by this commit https://github.com/cordova-sms/cordova-sms-plugin/commit/e9daef036a7de7b7ee4279a051f5e03f2d5e1c01 and this one https://github.com/cordova-sms/cordova-sms-plugin/commit/65218c33b5b782b230a402f0793571aea94887d0.

I believe this method could be cleaned and only keep the `Intent.ACTION_VIEW` intent. The main issue with Android is that third party applications can have crazy intent implementations, so there is no way for us to ensure 100% backward compatibility for all the users.

@aharris88, @brodybits, @kukikiloke thoughts?
